services:
  - type: web
    name: fintrack-app
    runtime: docker
    region: oregon
    plan: free
    dockerfile: Dockerfile
    dockerContext: .
    port: 5000
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
